### ISSUE TITLE
Parsing Teslim from Musecore musicxmls

### ISSUE THREAD

**Issue by JusticeV452** [dhmit/ottoman-sarki#2]
Now that we have the musescore musicxml files for the sarkis, we need a way to parse the Teslim and extract information relevant to inferring the makam.

Based on the current metrics we've discussed as relevant, we can start by making a function that takes an input of (path to the musicxml for a sarki) and returns a dictionary of the following format:

{
"start_note": first note of the Teslim (music21 Note object),
"end_note": last note of the Teslim (music21 Note),
"range": (lowest note in the Teslim, highest note of the Teslim) (pair of music21 Notes),
"accidentals": list of notes with accidentals in the order that they appear in the Teslim (list of music21 Notes)
}

**Comment by Annabelism** [comment]
I built a prototype for this task in the code folder, see find_teslim.ipynb

Some files return an Accidental-Exception-Error and I couldn't quite figure out why yet. If someone can also take a look when they get a chance that will be great!

**Comment by reeceyang** [comment]
music21 only allows some specific accidental names:
```python
['double-flat', 'double-sharp', 'flat', 'half-flat', 
'half-sharp', 'natural', 'one-and-a-half-flat', 'one-and-a-half-sharp', 
'quadruple-flat', 'quadruple-sharp', 'sharp', 'triple-flat', 'triple-sharp']
```

however our musicxml files have accidentals with other names, such as `slash-flat`. we might have to convert these accidentals into one of the corresponding musicxml accidental names for musicxml to be able to work with them.

musicxml also has a `allowNonStandardValue` parameter for it's Pitch class but I'm not sure how to enable it when reading xml from a file.

**Comment by reeceyang** [comment]
upon further inspection this might be a bug with music21's XML parser - it doesn't handle non-standard accidentals right now. Here's the stack trace for further reference:
```
File ~/cs/ottoman-sarki/code/venv/lib/python3.11/site-packages/music21/musicxml/xmlToM21.py:5708, in MeasureParser.xmlToKeySignature(self, mxKey)
   5706 # TODO: cancel
   5707 if mxKey.find('fifths') is None:
-> 5708     ks = self.nonTraditionalKeySignature(mxKey)
   5709 else:
   5710     ks = key.KeySignature()

File ~/cs/ottoman-sarki/code/venv/lib/python3.11/site-packages/music21/musicxml/xmlToM21.py:5838, in MeasureParser.nonTraditionalKeySignature(self, mxKey)
   5836     else:
   5837         accidentalName = thisAccidental
-> 5838     p.accidental = pitch.Accidental(accidentalName)
   5839     p.accidental.alter = thisAlter
   5840 else:

File ~/cs/ottoman-sarki/code/venv/lib/python3.11/site-packages/music21/pitch.py:906, in Accidental.__init__(self, specifier)
    904 self._alter = 0.0     # semitones to alter step
    905 # potentially can be a fraction... but not exponent...
--> 906 self.set(specifier)

File ~/cs/ottoman-sarki/code/venv/lib/python3.11/site-packages/music21/pitch.py:1170, in Accidental.set(self, name, allowNonStandardValue)
   1168 else:
   1169     if not allowNonStandardValue:
-> 1170         raise AccidentalException(f'{name} is not a supported accidental type')
   1172     if isinstance(name, str):
   1173         self._name = name

AccidentalException: slash-flat is not a supported accidental type
```

**Comment by JusticeV452** [comment]
As @reeceyang pointed out, after following the traceback, I also do not see a way to prompt the default importer to allow non-standard accidentals. One way we may be able to solve this is by subclassing the parser and making the tweaks necessary such that it allows non-standard values. This would involve subclassing
MusicXMLImporter, xmlPartToPart
PartParser, xmlMeasureToMeasure
MeasureParser, nonTraditionalKeySignature
Accidental __init__ or set
Does this sound reasonable, or does anyone have an alternative suggestion?
