### ISSUE TITLE
Parsing Makam List for One Key Signature

### ISSUE THREAD

**Issue by JusticeV452** [dhmit/ottoman-sarki#4]
In order to classify the Teslims extracted from the Sarkis, we'll need Python objects representing examples of each Makam to compare with.

As a starting point, let's create a dictionary mapping Makam to a dictionary in the following format (similar format used in issue #2)

{
"start_note": [first note (music21 Note object), ...],
"end_note": [last note (music21 Note), ...],
"range": [(lowest note, highest note) (pair of music21 Notes), ...],
"accidentals": [list of notes with accidentals in the order that they appear (list of music21 Notes), ...]
}

There should be an element in the list of each key, for each Makam variation in the Makam in One Key Signature file.

**Comment by reeceyang** [comment]
closed by https://github.com/dhmit/ottoman-sarki/commit/75ffb51f39bc56449a4fc01eb853fe4a1dfe3949

note that we also include a set of all pitches in the maqam in the dictionary (the `all_pitches` property)
